# Generated by Django 4.2.7 on 2026-06-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_channel', to='servers.channel')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_deafened', models.BooleanField(default=False)),
                ('is_speaking', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voice_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice.voicechannel')),
            ],
            options={
                'unique_together': {('user', 'voice_channel')},
            },
        ),
        migrations.AddField(
            model_name='voicechannel',
            name='connected_users',
            field=models.ManyToManyField(through='voice.VoiceConnection', to=settings.AUTH_USER_MODEL),
        ),
    ]
